version: "3.9"
services:
  tourify-api:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data:/app/data:rw
